version: "3.7"

services:
  flask-app:
    build: .
    volumes:
      - /Users/zach.stall/Downloads:/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - elasticsearch
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/mc    
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mc
    ports:
      - "5432:5432"

